name: ESLint

on:
  workflow_call:

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    permissions:
      checks: write
      actions: read
      contents: read
      packages: read
      statuses: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm run lint:export
        continue-on-error: true

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          report-json: 'eslint_report.json'
          markdown-report-on-step-summary: true
          check-name: ESLint Report
          repo-token: ${{ secrets.GITHUB_TOKEN }}
