name: Testing

on:
  pull_request:
    branches:
      - main

env:
  NEXT_TELEMETRY_DISABLED: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    permissions:
      checks: write
      # all these are just defaults, unsure which are necessary, but specifying any removes defaults
      actions: read
      contents: read
      deployments: read
      discussions: read
      issues: read
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: read
      statuses: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm run lint:export
        continue-on-error: true

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          report-json: 'eslint_report.json'
          markdown-report-on-step-summary: true
          check-name: ESLint Report
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm run lint:formatting

  typecheck:
    name: Type Checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm run type-check
